community_strategies <- function() {
  c(
    "alcohol_partially_attributable_acute",
    "alcohol_partially_attributable_chronic",
    "alcohol_wholly_attributable",
    "ambulatory_care_conditions_acute",
    "ambulatory_care_conditions_chronic",
    "ambulatory_care_conditions_vaccine_preventable",
    "emergency_elderly",
    "eol_care_2_days",
    "eol_care_3_to_14_days",
    "falls_related_admissions",
    "frail_elderly_high",
    "frail_elderly_intermediate",
    "intentional_self_harm",
    "medically_unexplained_related_admissions",
    "medicines_related_admissions_explicit",
    "medicines_related_admissions_implicit_anti-diabetics",
    "medicines_related_admissions_implicit_benzodiasepines",
    "medicines_related_admissions_implicit_diurectics",
    "medicines_related_admissions_implicit_nsaids",
    "obesity_related_admissions",
    "raid_ae",
    "raid_ip",
    "readmission_within_28_days",
    "smoking",
    "stroke_early_supported_discharge",
    # "virtual_wards_activity_avoidance_ari",
    # "virtual_wards_activity_avoidance_heart_failure",
    "virtual_wards_efficiencies_ari",
    "virtual_wards_efficiencies_heart_failure",
    "zero_los_no_procedure_adult",
    "zero_los_no_procedure_child"
  )
}
